
********************************************************************************
* Labeling variables ***********************************************************
********************************************************************************
// Endline 1 variable
label var jpc_attend_ec 	"Attended program if treated"
label var jpc_attend "Attended program if treated"
// treatment 
label var months_treated 		"Months since implementation"

// t2 
// what the fuck does t2 mean? 
// it means fucking land disputes. What the fuck. (land)"
label var anylndconf_u_ec2 		"Any serious land dispute"
label var unrslv_lnd_conf_u_ec2 "Any unresolved land dispute"
label var conf_m_house			"Length of house dispute (months)"
label var conf_m_farm 			"Length of farm dispute (months)"
label var conf_length_max_u_ec2	"Length of maximum land conflict phantom{}"
label var conf_length_mean_u_ec2	"Length of mean land conflict"
label var conf_any_u_ec2 		"Any threats, property damage, or violence"
label var conf_threat_u_ec2  	"\tab Threats"
label var conf_damage_u_ec2 	"\tab Property damage"
label var conf_viol_u_ec2 		"\tab Violence"
label var conf_witch_u_ec2 		"\tab Witchcraft"
label var conf_any_c_ec2 		"Any threats, property damage, or violence \phantom{}"
label var forum_lastsuc_c_ec2 	"Resolved land dispute"
label var conf_forum_c_ec2 		"\tab Number of forums used"
label var forum_inf_suc_c_ec2 	"\tab Resolved via informal mechanism"
label var forum_lastsat_c_ec2 	"\tab Satisfied with outcome"
label var conf_length_max_c_ec2	"Length of maximum land conflict"
label var conf_length_mean_c_ec2	"\tab Length of mean conflict"
label var conf_damage_c_ec2 	"\tab Property damage \phantom{}"
label var conf_viol_c_ec2 		"\tab Violence \phantom{}"
label var conf_threat_c_ec2 	"\tab Threats \phantom{}"
label var conf_witch_c_ec2 		"\tab Witchcraft \phantom{}"

// t2 
// what the fuck does t3 mean? 
// it means "all disputes" 
// money, land, and gender
label var lmg_conf_u_ec2 			"Any serious dispute"
label var lmg_unrslv_conf_u_ec2		"Any unresolved dispute"
label var lmg_conf_length_max_u_ec2	"Length of maximum conflict"
label var lmg_conf_length_mean_u_ec2	"\quad Length of mean conflict"
label var lmg_conf_any_u_ec2 		"\phantom{} Any threats, property damage, or violence"
label var lmg_conf_threat_u_ec2 	"\quad Threats"
label var lmg_conf_damage_u_ec2 	"\quad Property damage"
label var lmg_conf_viol_u_ec2 		"\quad Violence"
label var lmg_conf_witch_u_ec2 		"\quad Witchcraft"
label var lmg_forum_lastsuc_c_ec2 	"Resolved dispute"
label var lmg_conf_forum_c_ec2 		"\quad Number of forums used"
label var lmg_forum_inf_suc_c_ec2 	"\quad Resolved via informal mechanism"
label var lmg_forum_lastsat_c_ec2 	"\quad Satisfied with outcome"
label var lmg_conf_length_max_c_ec2	"Length of maximum conflict \phantom{}"
label var lmg_conf_length_mean_c_ec2	"\quad Length of mean conflict \phantom{}"
label var lmg_conf_times_ec2		"\quad Land dispute + gender dispute + money dispute"
label var mnyconf_any_u_ec2			"Any money conflict"
label var wmconf_any_u_ec2 			"Any man-woman conflict"
label var mnyconf_viol_u_ec2 		"Violence in money conflict"
label var wmconf_viol_u_ec2			"Violence in man-woman conflict"
label var lmg_conf_any_c_ec2        "\phantom{} Any threats, property damage, or violence \phantom{}"
label var lmg_conf_dam_violence_bin_c "\quad Property damage or violence \phantom{}"
label var lmg_conf_threat_c_ec2 "\quad Threats \phantom{}"
label var lmg_conf_viol_c_ec2 "\quad Violence \phantom{}"
label var lmg_conf_damage_c_ec2 "\quad Property damage \phantom{}"
label var lmg_conf_witch_c_ec2 "\quad Witchcraft \phantom{}"


// Fallow land
label var fallowland_farm 		"Index of Fallow Land for farm"
label var landrestpast  		"\quad Has ever let land rest"
label var landrestfut  			"\quad Will let land rest in future"
label var restseasons 			"\quad Num. of seasons to rest"
label var securerest  			"\quad Level of security if land resting"
label var size_farm 			"Size of farm"

label var security_rights 		"Security rights index for house and farm"
label var security_rights_farm	"\quad Security rights index for farm"
label var security_rights_house "\quad Security rights index for house"


label var improvez 				"Improvement index for house and farm"
label var improvez_farm			"\quad Improvement index for farm"
label var improvez_house 		"\quad Improvement index for house"

********************************************************************************
* Norms and Skills *************************************************************
********************************************************************************
label var all_cats_index_ec2 "Index of all norms combined"
label var bias_index_ec2 "\quad Bias index"
label var defection_index_ec2 "\quad Defection index"
label var empathy_index_ec2 "\quad Empathy index"
label var forum_choice_index_ec2 "\quad Forum choice index"
label var managing_emotions_index_ec2 "\quad Managing emotions index"
label var mediation_index_ec2 "\quad Mediation index"
label var negotiation_index_ec2 "\quad Negotiation index"


label var bias_index_el2 "Bias index"
label var defection_index_el2 "Defection index"
label var empathy_index_el2 "Empathy index"
label var forum_choice_index_el2 "Forum choice index"
label var managing_emotions_index_el2 "Managing emotions index"
label var mediation_index_el2 "Mediation index"
label var negotiation_index_el2 "Negotiation index"


* Just residents ***************************************************************
label var nospoilpropop_ec2 		"\quad Thinks shouldn't spoil property"		
label var nospoilpropco_ec2 		"\quad Comm thinks shouldn't spoil property"
label var skstaycalm_ec2 			"\quad Stays calm"
label var skcooltemper_ec2 			"\quad Cools temper"
label var sktalkbad_ec2 			"\quad Don't talk bad"
label var sktalkpalava_ec2 			"\quad Talks with opposing side"
label var sktalkgood_ec2 			"\quad Makes other side understand"
label var skproposesolution_ec2 	"\quad Proposes solution"
label var skhelpunderstand_ec2 		"\quad Helps others understand"
label var skcooltemperothers_ec2 	"\quad Cool others' temper"
label var nosmalllieop_ec2 			"\quad Thinks bad to tell lies"
label var nosmalllieco_ec2 			"\quad Comm. thinks bad to tell lies"
label var skbringtogether_ec2 		"\quad Bring others together"
label var skhelpagree_ec2 			"\quad Help others agree"
label var noadviseop_ec2 			"\quad Thinks good to ask friends for help"
label var noadviseco_ec2 			"\quad Comm thinks good to ask friends for help"
label var notalkfirstco_ec2 		"\quad Thinks good to talk to others first"
label var notalkfirstop_ec2 		"\quad Comm. thinks good to talk to others first"
label var nocommfirstop_ec2 		"\quad Thinks good to talk"
label var nocommfirstco_ec2 		"\quad Comm. thinks good to talk"
label var nopolicefirstco_ec2 		"\quad Comm doesn't think okay to go to police first"
label var nopolicefirstop_ec2 		"\quad Doesn't think okay to go to police first"
label var nomediateop_ec2  			"\quad Thinks its good to talk"
label var nocompromop_ec2 			"\quad Comm. thinks its good to talk"
label var nocompromco_ec2 			"\quad Thinks its good to talk"
label var nogiftop_ec2 				"\quad Thinks gifts okay"
label var nogiftco_ec2 				"\quad Comm. thinks gifts okay"
label var sklisten_ec2 				"\quad Listens to other side"
label var skconvincetalk_ec2 		"\quad Convinces other to talk"
label var skempathy_ec2 			"\quad Thinks about their side"
label var skthinkwrong_ec2 			"\quad Thinks might be wrong"
label var skthinkshoes_ec2 			"\quad Puts themselves in opposite shoes"
label var nochiefsupportop_ec2 		"\quad Thinks good to take palava to elders"
label var nochiefsupportco_ec2 		"\quad Comm. thinks good to take palava to elders"
label var nopoliceop_ec2 			"\quad Doesn't think okay to take palava to police"
label var nopoliceco_ec2 			"\quad Comm. doesnt think okay to take palava to police"
label var nocontactsop_ec2 			"\quad Thinks bad to take palava to biased forum"
label var nocontactsco_ec2 			"\quad Comm thinks bad to take palava to biased forum"
label var notalkfirstop_ec2 		"\quad Thinks good to go to good talkers first"
label var notakesideop_ec2 			"\quad Thinks bad to take sides"
label var notakesideco_ec2 			"\quad Comm thinks bad to take sides"
label var norenegeop_ec2 			"\quad Thinks bad to renege"
label var norenegeco_ec2 			"\quad Comm. thinks bad to renege"
label var nohelpcompop_ec2 			"\quad Thinks okay to help others"
label var nohelpcompco_ec2 			"\quad Comm thinks okay to help others"
label var skcompromise_ec2 			"\quad Compromizes with other"
label var skforgive_ec2				"\quad Forgives others"
label var nogossipop_ec2 			"\quad Thinks bad to gossip"
label var nogossipco_ec2 			"\quad Comm. thinks bad to gossip"
label var nomediateco_ec2 			"\quad Community brings people together in palava"


*Standardized Residents ********************************************************
label var nospoilpropop_st_ec2 			"\quad Thinks shouldn't spoil property (z-score)"
label var nospoilpropco_st_ec2 			"\quad Comm thinks shouldn't spoil property (z-score)"
label var skstaycalm_st_ec2 			"\quad Stays calm (z-score)"
label var skcooltemper_st_ec2 			"\quad Cools temper (z-score)"
label var sktalkbad_st_ec2 				"\quad Don't talk bad (z-score)"
label var sktalkpalava_st_ec2 			"\quad Talks with opposing side (z-score)"
label var sktalkgood_st_ec2 			"\quad Makes other side understand (z-score)"
label var skproposesolution_st_ec2 		"\quad Proposes solution (z-score)"
label var skhelpunderstand_st_ec2 		"\quad Helps others understand (z-score)"
label var skcooltemperothers_st_ec2 	"\quad Cool others' temper (z-score)"
label var nosmalllieop_st_ec2 			"\quad Thinks bad to tell lies (z-score)"
label var nosmalllieco_st_ec2 			"\quad Comm. thinks bad to tell lies (z-score)"
label var skbringtogether_st_ec2 		"\quad Bring others together (z-score)"
label var skhelpagree_st_ec2 			"\quad Help others agree (z-score)"
label var noadviseop_st_ec2 			"\quad Thinks good to ask friends for help (z-score)"
label var noadviseco_st_ec2 			"\quad Comm thinks good to ask friends for help (z-score)"
label var notalkfirstco_st_ec2 			"\quad Thinks good to talk to others first (z-score)"
label var notalkfirstop_st_ec2 			"\quad Comm. thinks good to talk to others first (z-score)"
label var nocommfirstop_st_ec2 			"\quad Thinks good to talk (z-score)"
label var nocommfirstco_st_ec2 			"\quad Comm. thinks good to talk (z-score)"
label var nopolicefirstco_st_ec2 		"\quad Comm doesn't think okay to go to police first (z-score)"
label var nopolicefirstop_st_ec2 		"\quad Doesn't think okay to go to police first (z-score)"
label var nomediateop_st_ec2  			"\quad Thinks its good to talk (z-score)"
label var nocompromop_st_ec2 			"\quad Comm. thinks its good to talk (z-score)"
label var nocompromco_st_ec2 			"\quad Thinks its good to talk (z-score)"
label var nogiftop_st_ec2 				"\quad Thinks gifts okay (z-score)"
label var nogiftco_st_ec2 				"\quad Comm. thinks gifts okay (z-score)"
label var sklisten_st_ec2 				"\quad Listens to other side (z-score)"
label var skconvincetalk_st_ec2 		"\quad Convinces other to talk (z-score)"
label var skempathy_st_ec2 				"\quad Thinks about their side (z-score)"
label var skthinkwrong_st_ec2 			"\quad Thinks might be wrong (z-score)"
label var skthinkshoes_st_ec2 			"\quad Puts themselves in opposite shoes (z-score)"
label var nochiefsupportop_st_ec2 		"\quad Thinks good to take palava to elders (z-score)"
label var nochiefsupportco_st_ec2 		"\quad Comm. thinks good to take palava to elders (z-score)"
label var nopoliceop_st_ec2 			"\quad Doesn't think okay to take palava to police (z-score)"
label var nopoliceco_st_ec2 			"\quad Comm. doesn't think okay to take palava to police (z-score)"
label var nocontactsop_st_ec2 			"\quad Thinks bad to take palava to biased forum (z-score)"
label var nocontactsco_st_ec2 			"\quad Comm thinks bad to take palava to biased forum (z-score)"
label var notalkfirstop_st_ec2 			"\quad Thinks good to go to good talkers first (z-score)"
label var notakesideop_st_ec2 			"\quad Thinks bad to take sides (z-score)"
label var notakesideco_st_ec2 			"\quad Comm thinks bad to take sides (z-score)"
label var norenegeop_st_ec2 			"\quad Thinks bad to renege (z-score)"
label var norenegeco_st_ec2 			"\quad Comm. thinks bad to renege (z-score)"
label var nohelpcompop_st_ec2 			"\quad Thinks okay to help others (z-score)"
label var nohelpcompco_st_ec2 			"\quad Comm thinks okay to help others (z-score)"
label var skcompromise_st_ec2 			"\quad Compromizes with other (z-score)"
label var skforgive_st_ec2				"\quad Forgives others (z-score)"
label var nogossipop_st_ec2 			"\quad Thinks bad to gossip (z-score)"
label var nogossipco_st_ec2 			"\quad Comm. thinks bad to gossip (z-score)"
label var nomediateco_st_ec2 			"\quad Community brings people together in palava (z-score)"


* Leaders **********************************************************************
label var nospoilpropop_el2 		"\quad Thinks shouldn't spoil property"		
label var nospoilpropco_el2 		"\quad Comm thinks shouldn't spoil property"
label var skstaycalm_el2 			"\quad Stays calm"
label var skcooltemper_el2 			"\quad Cools temper"
label var sktalkbad_el2 			"\quad Don't talk bad"
label var sktalkpalava_el2 			"\quad Talks with opposing side"
label var sktalkgood_el2 			"\quad Makes other side understand"
label var skproposesolution_el2 	"\quad Proposes solution"
label var skhelpunderstand_el2 		"\quad Helps others understand"
label var skcooltemperothers_el2 	"\quad Cool others' temper"
label var nosmalllieop_el2 			"\quad Thinks bad to tell lies"
label var nosmalllieco_el2 			"\quad Comm. thinks bad to tell lies"
label var skbringtogether_el2 		"\quad Bring others together"
label var skhelpagree_el2 			"\quad Help others agree"
label var noadviseop_el2 			"\quad Thinks good to ask friends for help"
label var noadviseco_el2 			"\quad Comm thinks good to ask friends for help"
label var notalkfirstco_el2 		"\quad Thinks good to talk to others first"
label var notalkfirstop_el2 		"\quad Comm. thinks good to talk to others first"
label var nocommfirstop_el2 		"\quad Thinks good to talk"
label var nocommfirstco_el2 		"\quad Comm. thinks good to talk"
label var nopolicefirstco_el2 		"\quad Comm doesn't think okay to go to police first"
label var nopolicefirstop_el2 		"\quad Doesn't think okay to go to police first"
label var nomediateop_el2  			"\quad Thinks its good to talk"
label var nocompromop_el2 			"\quad Comm. thinks its good to talk"
label var nocompromco_el2 			"\quad Thinks its good to talk"
label var nogiftop_el2 				"\quad Thinks gifts okay"
label var nogiftco_el2 				"\quad Comm. thinks gifts okay"
label var sklisten_el2 				"\quad Listens to other side"
label var skconvincetalk_el2 		"\quad Convinces other to talk"
label var skempathy_el2 			"\quad Thinks about their side"
label var skthinkwrong_el2 			"\quad Thinks might be wrong"
label var skthinkshoes_el2 			"\quad Puts themselves in opposite shoes"
label var nochiefsupportop_el2 		"\quad Thinks good to take palava to elders"
label var nochiefsupportco_el2 		"\quad Comm. thinks good to take palava to elders"
label var nopoliceop_el2 			"\quad Doesn't think okay to take palava to police"
label var nopoliceco_el2 			"\quad Comm. doesn't think okay to take palava to police"
label var nocontactsop_el2 			"\quad Thinks bad to take palava to biased forum"
label var nocontactsco_el2 			"\quad Comm thinks bad to take palava to biased forum"
label var notalkfirstop_el2 		"\quad Thinks good to go to good talkers first"
label var notakesideop_el2 			"\quad Thinks bad to take sides"
label var notakesideco_el2 			"\quad Comm thinks bad to take sides"
label var norenegeop_el2 			"\quad Thinks bad to renege"
label var norenegeco_el2 			"\quad Comm. thinks bad to renege"
label var nohelpcompop_el2 			"\quad Thinks okay to help others"
label var nohelpcompco_el2 			"\quad Comm thinks okay to help others"
label var skcompromise_el2 			"\quad Compromizes with other"
label var skforgive_el2				"\quad Forgives others"
label var nogossipop_el2 			"\quad Thinks bad to gossip"
label var nogossipco_el2 			"\quad Comm. thinks bad to gossip"
label var nomediateco_el2 			"\quad Community brings people together in palava"

* Standardized Leaders *********************************************************
label var nospoilpropop_st_el2 			"\quad Thinks shouldn't spoil property (z-score)"
label var nospoilpropco_st_el2 			"\quad Comm thinks shouldn't spoil property (z-score)"
label var skstaycalm_st_el2 			"\quad Stays calm (z-score)"
label var skcooltemper_st_el2 			"\quad Cools temper (z-score)"
label var sktalkbad_st_el2 				"\quad Don't talk bad (z-score)"
label var sktalkpalava_st_el2 			"\quad Talks with opposing side (z-score)"
label var sktalkgood_st_el2 			"\quad Makes other side understand (z-score)"
label var skproposesolution_st_el2 		"\quad Proposes solution (z-score)"
label var skhelpunderstand_st_el2 		"\quad Helps others understand (z-score)"
label var skcooltemperothers_st_el2 	"\quad Cool others' temper (z-score)"
label var nosmalllieop_st_el2 			"\quad Thinks bad to tell lies (z-score)"
label var nosmalllieco_st_el2 			"\quad Comm. thinks bad to tell lies (z-score)"
label var skbringtogether_st_el2 		"\quad Bring others together (z-score)"
label var skhelpagree_st_el2 			"\quad Help others agree (z-score)"
label var noadviseop_st_el2 			"\quad Thinks good to ask friends for help (z-score)"
label var noadviseco_st_el2 			"\quad Comm thinks good to ask friends for help (z-score)"
label var notalkfirstco_st_el2 			"\quad Thinks good to talk to others first (z-score)"
label var notalkfirstop_st_el2 			"\quad Comm. thinks good to talk to others first (z-score)"
label var nocommfirstop_st_el2 			"\quad Thinks good to talk (z-score)"
label var nocommfirstco_st_el2 			"\quad Comm. thinks good to talk (z-score)"
label var nopolicefirstco_st_el2 		"\quad Comm thinks good to go to police first (z-score)"
label var nopolicefirstop_st_el2 		"\quad Tinks good to go to police first (z-score)"
label var nomediateop_st_el2  			"\quad Thinks its good to talk (z-score)"
label var nocompromop_st_el2 			"\quad Comm. thinks its good to talk (z-score)"
label var nocompromco_st_el2 			"\quad Thinks its good to talk (z-score)"
label var nogiftop_st_el2 				"\quad Thinks gifts okay (z-score)"
label var nogiftco_st_el2 				"\quad Comm. thinks gifts okay (z-score)"
label var sklisten_st_el2 				"\quad Listens to other side (z-score)"
label var skconvincetalk_st_el2 		"\quad Convinces other to talk (z-score)"
label var skempathy_st_el2 				"\quad Thinks about their side (z-score)"
label var skthinkwrong_st_el2 			"\quad Thinks might be wrong (z-score)"
label var skthinkshoes_st_el2 			"\quad Puts themselves in opposite shoes (z-score)"
label var nochiefsupportop_st_el2 		"\quad Thinks good to take palava to elders (z-score)"
label var nochiefsupportco_st_el2 		"\quad Comm. thinks good to take palava to elders (z-score)"
label var nopoliceop_st_el2 			"\quad Thinks good to take palava to police (z-score)"
label var nopoliceco_st_el2 			"\quad Comm. thinks good to take palava to police (z-score)"
label var nocontactsop_st_el2 			"\quad Thinks bad to take palava to biased forum (z-score)"
label var nocontactsco_st_el2 			"\quad Comm thinks bad to take palava to biased forum (z-score)"
label var notalkfirstop_st_el2 			"\quad Thinks good to go to good talkers first (z-score)"
label var notakesideop_st_el2 			"\quad Thinks bad to take sides (z-score)"
label var notakesideco_st_el2 			"\quad Comm thinks bad to take sides (z-score)"
label var norenegeop_st_el2 			"\quad Thinks bad to renege (z-score)"
label var norenegeco_st_el2 			"\quad Comm. thinks bad to renege (z-score)"
label var nohelpcompop_st_el2 			"\quad Thinks okay to help others (z-score)"
label var nohelpcompco_st_el2 			"\quad Comm thinks okay to help others (z-score)"
label var skcompromise_st_el2 			"\quad Compromizes with other (z-score)"
label var skforgive_st_el2				"\quad Forgives others (z-score)"
label var nogossipop_st_el2 			"\quad Thinks bad to gossip (z-score)"
label var nogossipco_st_el2 			"\quad Comm. thinks bad to gossip (z-score)"
label var nomediateco_st_el2 			"\quad Community brings people together in palava (z-score)"


********************************************************************************
* Variables bout community disputes ********************************************
********************************************************************************
label var anyviol_el2 				"Any Violence"
label var sumviol_el2 				"Level of community violence"
label var tribviol_dum_el2			"\quad Intertribal violence"
label var strkviol_dum_el2 			"\quad Violent strike or protest"
label var pvytheld_dum_el2  		"\quad Youth-elder dispute"
label var strkpeac_dum_el2 			"\quad Peaceful strike or protest"
label var cfamlndcn_dum_el2  		"\quad Interfamily land disputes"
label var dtwnldcn_dum_el2  		"\quad Conflicts with other towns"
label var suspwitc_dum_el2 			"\quad Witch hunts"
label var sasycutl_dum_el2 			"\quad Trial by ordeal"
label var sasywitch_el2 			"\quad Witch hunt or trial by ordeal"

***
label var age_bc "Age"
label var male_bc "Male"
label var yrs_edu_bc "Years of education"
label var muslim_bc "Muslim"
label var traditional_bc "Traditional religion"
label var christian_bc "christian"
label var wealthindex_bc "Wealth index"
label var landless_bc "Landless"
label var farmless_bc "No farm"
label var anypeace_bc "Prior peace education"
label var gpeace_bc "Participating in a peace group"
label var refugee_bc "Refugee"
label var displaced_bc "Displaced"
label var viol_experienced_bc "Violence experience index (0-13)"
label var lndtake_dum_bc "House spot or farmland taken during war"
label var landconf_dummy_bc "Any land conflict since end of war"
label var moneyconflict_bc "Had a money conflict in 2008"
label var crime_dummy_bc "Any burglary or armed robbery in 2008"
label var witchcraft_dummy_bc "Victim of witchcraft in 2008"
label var palawater_dum_bc "Had a dispute at a water source in past 6 mo."


label var ctownpop_bl "Town population"
label var cedulevel_bc "Town education level"
label var cnum_tribes_bc "Number of tribes in town"
label var cprop_domgroup_bc "\% of community members in largest tribe"
label var cwealthindex_bc "Town wealth index"
label var cfacilities_bl "# of services available in town (0-14)"
label var ctot_resources_bl "# of resources within 2 hrs of comm. (0-5)"
label var croad_dist_rainy_bl "Distance to nearest road in hours, rainy season"
label var cviol_experienced_bc "Town exposure to war violence"
label var clndtake_bc "\% of town losing land during war"
label var cprog_ldr_beliefs_bc "Index of progressive political beliefs in town"
label var cattitudes_tribe_bc "Index of progressive ethnic attitudes in town"
label var canypeace_bc "\% of town with prior peace education"
label var cgpeace_bc "\% of town participating in a peace group"
label var crelmarry_bc "\% of town accepting of inter-religious marriage"
label var cviol_scale_bc "\% of town reporting assault"
label var clandconf_scale_bc "\% of town reporting a land dispute"
label var cwitchcraft_scale_bc "\% of town reporting witchcraft victimization"
label var cpalaviol_imputed_bc "\% of town reporting "
label var cstrkpeac_dummy_bl "\% of town reporting violent dispute at water source"
label var ccoll_viol_bl "Violent strike or ethnic dispute in town"
label var ctribal_conf_bl "Witch killing or tral by ordeal in town"
label var ccapital_offense_bl "Rape or murder in town"
***